version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    volumes:
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14 
    shm_size: '1gb'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: silver3456/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSWER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml  
    volumes:
      - ./output/search-result1:/usr/share/udemy/test-output
  book-flight-module:
    image: silver3456/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSWER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/book-result1:/usr/share/udemy/test-output